name: Deploy ERP to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: docker:dind
      options: --privileged # Required for Docker-in-Docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock # Optional: Use host Docker daemon
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apk add --no-cache bash git docker-compose
        # Note: docker:dind uses Alpine Linux, so we use apk to install packages


      - name: Build and Deploy Docker Compose
        run: |
          docker-compose version
         
        working-directory: ${{ github.workspace }}

      - name: Clean up Docker
        run: |
          docker image prune -f
          docker container prune -f
        working-directory: ${{ github.workspace }}
        if: always()
